name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

env:
  RELEASE_TAG: ${{ github.ref_name }}

jobs:
  build-linux:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.22.0'

      - name: Install Dependencies (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libgtk-3-dev libglu1-mesa-dev libsoil-dev
          sudo apt-get install -y libwxgtk3.0-gtk3-dev wx3.0-headers wx-common

      - name: Create build directory
        run: mkdir -p build

      - name: Configure CMake
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DwxWidgets_ROOT_DIR=/usr/lib/x86_64-linux-gnu/wx -DwxWidgets_CONFIG_EXECUTABLE=/usr/bin/wx-config

      - name: Build Project (Linux)
        run: cmake --build build --config Release

      - name: Compress Release Directory (Linux)
        run: |
          cd build
          tar -czvf deeprey_linux_${{ env.RELEASE_TAG }}.tar.gz release

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.1.1
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          release_name: "Release ${{ env.RELEASE_TAG }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Linux Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/deeprey_linux_${{ env.RELEASE_TAG }}.tar.gz
          asset_name: deeprey_linux_${{ env.RELEASE_TAG }}.tar.gz
          asset_content_type: application/gzip

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.22.0'

      - name: Install Dependencies (Windows)
        run: |
          choco install wxwidgets --version=3.1.5
          mkdir libs/SOIL
          curl -L -o libs/SOIL/SOIL.zip https://github.com/littlstar/SOIL/archive/refs/heads/main.zip
          powershell -Command "Expand-Archive libs/SOIL/SOIL.zip -DestinationPath libs/SOIL/"
          move libs/SOIL/SOIL-main/* libs/SOIL/

      - name: Create build directory
        run: mkdir -p build

      - name: Configure CMake
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build Project (Windows)
        run: cmake --build build --config Release

      - name: Compress Release Directory (Windows)
        run: |
          cd build
          powershell Compress-Archive -Path release -DestinationPath deeprey_windows_${{ env.RELEASE_TAG }}.zip

      - name: Upload Windows Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/deeprey_windows_${{ env.RELEASE_TAG }}.zip
          asset_name: deeprey_windows_${{ env.RELEASE_TAG }}.zip
          asset_content_type: application/zip
