name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.22.0'

      - name: Install Dependencies (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libgtk-3-dev libglu1-mesa-dev libsoil-dev
          sudo apt-get install -y libwxgtk3.0-gtk3-dev wx3.0-headers wx-common

      - name: Create build directory
        run: mkdir -p build

      - name: Configure CMake
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DwxWidgets_ROOT_DIR=/usr/lib/x86_64-linux-gnu/wx -DwxWidgets_CONFIG_EXECUTABLE=/usr/bin/wx-config

      - name: Build Project (Linux)
        run: cmake --build build --config Release

      - name: Compress Release Directory (Linux)
        run: |
          cd build
          tar -czvf release-linux.tar.gz release

      - name: Create Release (Linux)
        id: create_release_linux
        uses: actions/create-release@v1.1.1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset (Linux)
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release_linux.outputs.upload_url }}
          asset_path: build/release-linux.tar.gz
          asset_name: release-linux.tar.gz
          asset_content_type: application/gzip

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.22.0'

      - name: Install Dependencies (Windows)
        run: |
          choco install wxwidgets --version=3.1.5
          mkdir libs/SOIL
          curl -L -o libs/SOIL/SOIL.zip https://github.com/littlstar/SOIL/archive/refs/heads/main.zip
          powershell -Command "Expand-Archive libs/SOIL/SOIL.zip -DestinationPath libs/SOIL/"
          move libs/SOIL/SOIL-main/* libs/SOIL/

      - name: Create build directory
        run: mkdir -p build

      - name: Configure CMake
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build Project (Windows)
        run: cmake --build build --config Release

      - name: Compress Release Directory (Windows)
        run: |
          cd build
          powershell Compress-Archive -Path release -DestinationPath release-windows.zip

      - name: Create Release (Windows)
        id: create_release_windows
        uses: actions/create-release@v1.1.1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset (Windows)
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release_windows.outputs.upload_url }}
          asset_path: build/release-windows.zip
          asset_name: release-windows.zip
          asset_content_type: application/zip
