name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.16.0'

      - name: Set up wxWidgets (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwxgtk3.0-gtk3-dev libsoil-dev

      - name: Set up wxWidgets and SOIL (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install wxwidgets --version=3.1.5
          mkdir libs/SOIL
          curl -L -o libs/SOIL/SOIL.zip https://github.com/littlstar/SOIL/archive/refs/heads/main.zip
          powershell -Command "Expand-Archive libs/SOIL/SOIL.zip -DestinationPath libs/SOIL/"
          move libs/SOIL/SOIL-main/* libs/SOIL/

      - name: Create build directory
        run: mkdir build

      - name: Configure CMake
        run: cmake .. -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build Project
        run: cmake --build build --config Release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3.1.0  # Explicit version
        with:
          name: wxOpenGLApp-${{ matrix.os }}-build
          path: build/release/
